name: CI

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'img/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'img/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build-emscripten:
    runs-on: ubuntu-${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [20.04, 22.04]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get -y update
      - uses: mymindstorm/setup-emsdk@v14
      - name: Build
        run: make -j$(nproc)
      - name: Upload game (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.targetos }}-${{ matrix.targetarch }}
          path: |
            ./build/*
  download:
    needs: build-emscripten
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ghpages
    - name: Setup Node & NPM
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        path: ./
        pattern: artifact-*
        merge-multiple: true
    - name: Uglify JS for faster runtime
      run: |
          npm install uglify-js -g
          uglifyjs deobfuscated.js -c > deobfuscated.js.min
          uglifyjs smolnes.js -c > smolnes.js.min
          rm smolnes.js deobfuscated.js
          mv deobfuscated.js.min deobfuscated.js
          mv smolnes.js.min smolnes.js
    - name: Push to GH Pages
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update GH Pages as per master branch"
          git push
